spring:
  application:
    name: springspecialist
  datasource:
#    url: jdbc:mysql://localhost:3306/springspecialist
    url: jdbc:h2:mem:products
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console